### ISSUE TITLE
Conflict with other dependencies

### ISSUE THREAD

**Issue by Sparks1998** [enyo/stripe-dart#21]
The dependency conflicts with some dependencies that need http: ^1.x.x since this dependency depends on 0.13.0.

**Comment by oboobortot** [comment]
I really don'y understand why this is not merged? I drags HTTP package to be fixed to 0.13.1 which leads to intl to be fixed with older version and generally dragging a who chain of dependencies down.

**Comment by illia-romanenko** [comment]
We removed that dependency completely, so you can link to GitHub instead pub.dev. 

I would love to push an update to pub.dev but there were some issues with @enyo 's invite for me to pub. I hope that he will be able to get back to it and re-send it.
